#! /bin/bash
let sum=0
for num in 1 2 3 4 5
do
    let "sum = $sum + $num"
done
echo $sum

pet=(dog cat fish)

for x in ${pet[*]}
do
    echo $x
done

echo "Enter a number: "; read x
let sum=0
for(( i=1; $i<=$x; i=$i+1 )); do
    let "sum = $sum+$i"
done
echo "the sum of the first $x numbers is: $sum"
